# Generated by Django 4.2.6 on 2023-10-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0005_book_readers_alter_book_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="my_books",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
